name: Garmin同步

on:
  schedule:
    - cron: "0 2 * * *"  # 每天北京时间10点自动同步
  workflow_dispatch:     # 可手动点击运行

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: 安装依赖
        run: pip install -r requirements.txt
      - name: 开始同步
        env:
          GARMIN_INTL_EMAIL: ${{ secrets.GARMIN_INTL_EMAIL }}
          GARMIN_INTL_PASSWORD: ${{ secrets.GARMIN_INTL_PASSWORD }}
          GARMIN_CN_EMAIL: ${{ secrets.GARMIN_CN_EMAIL }}
          GARMIN_CN_PASSWORD: ${{ secrets.GARMIN_CN_PASSWORD }}
        run: python sync.py
